"""initial schema

Revision ID: b73c676f04f7
Revises:
Create Date: 2026-08-08 12:46:27.201349+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b73c676f04f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collector_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collector_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=False),
        sa.Column("finished_at", sa.String(length=32), nullable=True),
        sa.Column("scroll_passes", sa.Integer(), nullable=False),
        sa.Column("exhausted", sa.Integer(), nullable=False),
        sa.Column("advanced_checkpoint", sa.Integer(), nullable=False),
        sa.Column("stopped_because", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("items_seen", sa.Integer(), nullable=False),
        sa.Column("items_new", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('ok', 'auth_required', 'blocked', 'empty')",
            name="ck_collector_runs_outcome",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collector_runs", schema=None) as batch_op:
        batch_op.create_index("idx_runs_collector", ["collector_id", "started_at"], unique=False)

    op.create_table(
        "items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("platform_item_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.String(length=32), nullable=False),
        sa.Column("source_published_at", sa.String(length=32), nullable=True),
        sa.Column("action_at", sa.String(length=32), nullable=True),
        sa.Column("checked_at", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "kind IN ('repo', 'model', 'paper', 'demo', 'tool', 'post', 'product', 'outfit')",
            name="ck_items_kind",
        ),
        sa.CheckConstraint(
            "platform IN ('github', 'huggingface', 'arxiv', 'threads', 'linkedin', 'instagram', 'web')",
            name="ck_items_platform",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url", name="uq_items_canonical_url"),
        sa.UniqueConstraint("platform", "platform_item_id", name="uq_items_platform_id"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index("idx_items_first_seen", ["first_seen_at"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "source_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("handle", sa.String(length=255), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Integer(), nullable=False),
        sa.Column("connected_at", sa.String(length=32), nullable=True),
        sa.Column("last_ok_at", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "platform IN ('github', 'huggingface', 'arxiv', 'threads', 'linkedin', 'instagram', 'web')",
            name="ck_source_accounts_platform",
        ),
        sa.CheckConstraint(
            "state IN ('collected', 'skipped', 'auth_required', 'failed', 'disabled')",
            name="ck_source_accounts_state",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "handle", name="uq_source_accounts_platform_handle"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("collector_id", sa.String(length=64), nullable=False),
        sa.Column("source_account_id", sa.Integer(), nullable=True),
        sa.Column("last_seen_code", sa.String(length=64), nullable=True),
        sa.Column("last_outcome", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "last_outcome IN ('ok', 'auth_required', 'blocked', 'empty', 'never_run')",
            name="ck_checkpoints_outcome",
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("collector_id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("provenance", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "provenance IN ('fact', 'inference', 'external')", name="ck_evidence_provenance"
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_evidence_confidence",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index("idx_evidence_item", ["item_id"], unique=False)

    op.create_table(
        "item_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("source_account_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=16), nullable=True),
        sa.Column("collection_name", sa.String(length=64), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.String(length=32), nullable=False),
        sa.Column("action_at", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "action_type IS NULL OR action_type IN ('star', 'like', 'save', 'repost')",
            name="ck_item_sources_action_type",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id", "source_account_id", "collection_name", name="uq_item_sources_membership"
        ),
    )
    with op.batch_alter_table("item_sources", schema=None) as batch_op:
        batch_op.create_index(
            "idx_item_sources_collection", ["collection_name", "position"], unique=False
        )

    op.create_table(
        "item_tags",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("tag", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "tag"),
    )
    with op.batch_alter_table("item_tags", schema=None) as batch_op:
        batch_op.create_index("idx_item_tags_tag", ["tag"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("current_step", sa.String(length=128), nullable=True),
        sa.Column("cancellable", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=True),
        sa.Column("finished_at", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'partially_succeeded', 'failed', 'cancelled', 'blocked')",
            name="ck_jobs_state",
        ),
        sa.CheckConstraint(
            "type IN ('collection', 'enrichment', 'build', 'run', 'price', 'cleanup')",
            name="ck_jobs_type",
        ),
        sa.ForeignKeyConstraint(["target_id"], ["items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("idx_jobs_state", ["state", "created_at"], unique=False)

    op.create_table(
        "media_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("remote_url", sa.Text(), nullable=True),
        sa.Column("remote_expires_at", sa.String(length=32), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "role", name="uq_media_item_role"),
    )
    op.create_table(
        "raw_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("platform_item_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "platform IN ('github', 'huggingface', 'arxiv', 'threads', 'linkedin', 'instagram', 'web')",
            name="ck_raw_events_platform",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["collector_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "platform", "platform_item_id", name="uq_raw_events_run_item"
        ),
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("at", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.create_index("idx_job_events_job", ["job_id", "at"], unique=False)

    op.create_table(
        "job_steps",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=True),
        sa.Column("finished_at", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('waiting', 'running', 'done', 'failed', 'skipped')",
            name="ck_job_steps_state",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_steps", schema=None) as batch_op:
        batch_op.create_index("idx_job_steps_job", ["job_id", "ordinal"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_steps", schema=None) as batch_op:
        batch_op.drop_index("idx_job_steps_job")

    op.drop_table("job_steps")
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.drop_index("idx_job_events_job")

    op.drop_table("job_events")
    op.drop_table("raw_events")
    op.drop_table("media_assets")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_jobs_state")

    op.drop_table("jobs")
    with op.batch_alter_table("item_tags", schema=None) as batch_op:
        batch_op.drop_index("idx_item_tags_tag")

    op.drop_table("item_tags")
    with op.batch_alter_table("item_sources", schema=None) as batch_op:
        batch_op.drop_index("idx_item_sources_collection")

    op.drop_table("item_sources")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index("idx_evidence_item")

    op.drop_table("evidence")
    op.drop_table("checkpoints")
    op.drop_table("source_accounts")
    op.drop_table("settings")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index("idx_items_first_seen")

    op.drop_table("items")
    with op.batch_alter_table("collector_runs", schema=None) as batch_op:
        batch_op.drop_index("idx_runs_collector")

    op.drop_table("collector_runs")
    # ### end Alembic commands ###
